# Generated by Django 3.2.9 on 2021-12-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='not_owned_products',
            field=models.ManyToManyField(null=True, to='api.Product'),
        ),
    ]
