# Generated by Django 3.2.9 on 2021-12-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_not_owned_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='not_owned_products',
            field=models.ManyToManyField(blank=True, to='api.Product'),
        ),
    ]
